module.exports = {
	SCREEN_RATIO: 16 / 9,
	PLAYER_SPEED: 0.3,
	PLAYER_ROTATION_SPEED: 0.03,
	MAX_AMOUNT_OF_CLIENTS: 4,
	MIN_AMOUNT_OF_CLIENTS: 1,
	LOOP_INTERVAL_TIME: 1000 / 120,
	ACCELARATION_FACTOR: 0.001,
	MISSILE_SPEED: 0.153,
	INTERACTION_PAUSE: 50, //ms
	PLAYER_COLORS: ['green', 'red', 'yellow', 'pink']
}