# Install node@12
FROM node:12

# Set workdir to "app"
WORKDIR /app

# Copy package.json into docker environment
COPY package*.json /app

# Install dependencies
RUN npm install

# Copy source code
COPY . /app

# Expose port 8080
EXPOSE 8081

# Run command to start the server
CMD [ "node", "server.js" ]
